name: flutter_prolead_file_example
description: Example application for flutter_prolead_file SDK.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_prolead_file:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
